title="Camera"
author="Hyla"
perms=["camera", "files"]
version="1.0.0"
description="Take photos from your webcam using the Camera app!
---- IMPORTANT ----
DO NOT USE IF YOUR ADMINISTRATOR BANS CAMERA USAGE."