title="Eggnet"
author="SpinningCubes"
perms=["files", "notifications"]
version="1.2.0"
description="Chat with others with Eggnet.
- Privacy-based
- Peer-to-peer
- No backend servers! Simply enter your friend's code and connect!

And, it's free!"