title="Synthesizer"
author="SpinningCubes"
perms=["midi"]
version="1.0.0"
description="Synthesize with the Synthesizer app!
With this app, you can even hook up REAL MIDI intruments and play some tunes!"